version: 1.0.{build}
os: Visual Studio 2015
clone_folder: C:\projects\libcmaes
test: off
configuration:
    - Release
branches:
  only:
    - master
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
install:
  - cinstall: python
  - appveyor-retry appveyor DownloadFile http://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz
  - 7z x 3.3.3.tar.gz -oc:\projects > nul
  - 7z x c:\projects\3.3.3.tar -oc:\projects > nul
  - cd c:\projects\eigen-eigen-f562a193118d
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_INSTALL_PREFIX=c:\Libraries\eigen -DCMAKE_BUILD_TYPE=%Configuration% ..
  - cmake --build . --config %Configuration% --target install
  - cd c:\projects\libcmaes
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_INSTALL_PREFIX=c:\Libraries\libcmaes -DCMAKE_BUILD_TYPE=%Configuration% -DEigen3_DIR=c:\Libraries\eigen\share\eigen3\cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_PYTHON=OFF .
  - cmake --build . --config %Configuration% --target install
  - ctest -C %Configuration%
